name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Anime
        uses: lowlighter/metrics@latest
        with:
          filename: anime.svg
          base: ""
          config_order: anilist
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_anilist: yes
          plugin_anilist_user:  ${{ secrets.ANILIST }}
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
      - name: Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: skyline.svg
          base: ""
          token: ${{ secrets.TOKEN }}
          plugin_skyline: yes
          plugin_skyline_quality: 1
          
